name: "Build Tool"

permissions:
  contents: write
  discussions: write

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build-win:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4.1.7
      - name: Set up Python 3.11
        uses: actions/setup-python@v5.1.1
        with:
          python-version: "3.11"
          architecture: "x64"
          cache: 'pip'
      - name: Build tool
        run: |
          python build.py
      - name: Upload Win Build
        if: success()
        uses: actions/upload-artifact@v4.3.5
        with:
          name: TIK-win
          path: "./TIK-win.zip"

  build-linux:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4.1.7
      - name: Set up Python
        uses: actions/setup-python@v5.1.1
        with:
          python-version: "3.11"
          architecture: "x64"
          cache: 'pip'
      - name: Build Tool
        run: |
          python3 build.py
      - name: Upload Linux Build
        if: success()
        uses: actions/upload-artifact@v4.3.5
        with:
          name: TIK-linux
          path: "./TIK-linux.zip"
